// Date: 8/5/2016 12:03:11 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.cubic_control.overload.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEnderMech extends ModelBase
{
  //fields
    ModelRenderer LegL;
    ModelRenderer LegR;
    ModelRenderer FootL;
    ModelRenderer FootR;
    ModelRenderer HeelL;
    ModelRenderer HeelR;
    ModelRenderer Hip;
    ModelRenderer Torso;
    ModelRenderer Chest;
    ModelRenderer ShoulderL;
    ModelRenderer ShoulderR;
    ModelRenderer Neck;
    ModelRenderer UpperArmL;
    ModelRenderer UpperArmR;
    ModelRenderer ForeArmL;
    ModelRenderer ForeArmR;
    ModelRenderer ClawPart1;
    ModelRenderer ClawPart2;
    ModelRenderer ClawPart3;
    ModelRenderer ClawPart4;
    ModelRenderer ClawPart5;
    ModelRenderer SightF;
    ModelRenderer SightB;
    ModelRenderer Head;
    ModelRenderer AntenaL;
    ModelRenderer AntenaR;
    ModelRenderer ExoSpineB;
    ModelRenderer ExoSpineF;
    ModelRenderer Chip;
  
  public ModelEnderMech()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      LegL = new ModelRenderer(this, 0, 0);
      LegL.addBox(0F, 0F, 0F, 5, 15, 5);
      LegL.setRotationPoint(1F, 9F, -2F);
      LegL.setTextureSize(64, 64);
      LegL.mirror = true;
      setRotation(LegL, 0F, 0F, 0F);
      LegR = new ModelRenderer(this, 0, 0);
      LegR.addBox(0F, 0F, 0F, 5, 15, 5);
      LegR.setRotationPoint(-6F, 9F, -2F);
      LegR.setTextureSize(64, 64);
      LegR.mirror = true;
      setRotation(LegR, 0F, 0F, 0F);
      FootL = new ModelRenderer(this, 20, 0);
      FootL.addBox(0F, 0F, 0F, 5, 2, 3);
      FootL.setRotationPoint(1F, 22F, -5F);
      FootL.setTextureSize(64, 64);
      FootL.mirror = true;
      setRotation(FootL, 0F, 0F, 0F);
      FootR = new ModelRenderer(this, 20, 0);
      FootR.addBox(0F, 0F, 0F, 5, 2, 3);
      FootR.setRotationPoint(-6F, 22F, -5F);
      FootR.setTextureSize(64, 64);
      FootR.mirror = true;
      setRotation(FootR, 0F, 0F, 0F);
      HeelL = new ModelRenderer(this, 20, 5);
      HeelL.addBox(0F, 0F, 0F, 5, 1, 1);
      HeelL.setRotationPoint(1F, 23F, 3F);
      HeelL.setTextureSize(64, 64);
      HeelL.mirror = true;
      setRotation(HeelL, 0F, 0F, 0F);
      HeelR = new ModelRenderer(this, 20, 5);
      HeelR.addBox(0F, 0F, 0F, 5, 1, 1);
      HeelR.setRotationPoint(-6F, 23F, 3F);
      HeelR.setTextureSize(64, 64);
      HeelR.mirror = true;
      setRotation(HeelR, 0F, 0F, 0F);
      Hip = new ModelRenderer(this, 0, 20);
      Hip.addBox(0F, 0F, 0F, 10, 5, 7);
      Hip.setRotationPoint(-5F, 4F, -3F);
      Hip.setTextureSize(64, 64);
      Hip.mirror = true;
      setRotation(Hip, 0F, 0F, 0F);
      Torso = new ModelRenderer(this, 36, 0);
      Torso.addBox(0F, 0F, 0F, 8, 10, 5);
      Torso.setRotationPoint(-4F, -6F, -2F);
      Torso.setTextureSize(64, 64);
      Torso.mirror = true;
      setRotation(Torso, 0F, 0F, 0F);
      Chest = new ModelRenderer(this, 0, 32);
      Chest.addBox(0F, 0F, 0F, 10, 5, 7);
      Chest.setRotationPoint(-5F, -11F, -3F);
      Chest.setTextureSize(64, 64);
      Chest.mirror = true;
      setRotation(Chest, 0F, 0F, 0F);
      ShoulderL = new ModelRenderer(this, 8, 44);
      ShoulderL.addBox(0F, 0F, 0F, 1, 3, 3);
      ShoulderL.setRotationPoint(5F, -10F, -1F);
      ShoulderL.setTextureSize(64, 64);
      ShoulderL.mirror = true;
      setRotation(ShoulderL, 0F, 0F, 0F);
      ShoulderR = new ModelRenderer(this, 0, 44);
      ShoulderR.addBox(0F, 0F, 0F, 1, 3, 3);
      ShoulderR.setRotationPoint(-6F, -10F, -1F);
      ShoulderR.setTextureSize(64, 64);
      ShoulderR.mirror = true;
      setRotation(ShoulderR, 0F, 0F, 0F);
      Neck = new ModelRenderer(this, 16, 44);
      Neck.addBox(0F, 0F, 0F, 4, 1, 4);
      Neck.setRotationPoint(-2F, -12F, -2F);
      Neck.setTextureSize(64, 64);
      Neck.mirror = true;
      setRotation(Neck, 0F, 0F, 0F);
      UpperArmL = new ModelRenderer(this, 34, 25);
      UpperArmL.addBox(0F, 0F, 0F, 3, 5, 5);
      UpperArmL.setRotationPoint(6F, -11F, -2F);
      UpperArmL.setTextureSize(64, 64);
      UpperArmL.mirror = true;
      setRotation(UpperArmL, 0F, 0F, 0F);
      UpperArmR = new ModelRenderer(this, 34, 15);
      UpperArmR.addBox(0F, 0F, 0F, 3, 5, 5);
      UpperArmR.setRotationPoint(-9F, -11F, -2F);
      UpperArmR.setTextureSize(64, 64);
      UpperArmR.mirror = true;
      setRotation(UpperArmR, 0F, 0F, 0F);
      ForeArmL = new ModelRenderer(this, 18, 50);
      ForeArmL.addBox(0F, 0F, 0F, 4, 9, 5);
      ForeArmL.setRotationPoint(5.5F, -6F, -2F);
      ForeArmL.setTextureSize(64, 64);
      ForeArmL.mirror = true;
      setRotation(ForeArmL, 0F, 0F, 0F);
      ForeArmR = new ModelRenderer(this, 0, 50);
      ForeArmR.addBox(0F, 0F, 0F, 4, 9, 5);
      ForeArmR.setRotationPoint(-9.5F, -6F, -2F);
      ForeArmR.setTextureSize(64, 64);
      ForeArmR.mirror = true;
      setRotation(ForeArmR, 0F, 0F, 0F);
      ClawPart1 = new ModelRenderer(this, 20, 16);
      ClawPart1.addBox(0F, 0F, 0F, 1, 3, 1);
      ClawPart1.setRotationPoint(-8F, 3F, 0F);
      ClawPart1.setTextureSize(64, 64);
      ClawPart1.mirror = true;
      setRotation(ClawPart1, 0F, 0F, 0F);
      ClawPart2 = new ModelRenderer(this, 20, 16);
      ClawPart2.addBox(0F, 0F, 0F, 1, 3, 1);
      ClawPart2.setRotationPoint(-8F, 6F, 1F);
      ClawPart2.setTextureSize(64, 64);
      ClawPart2.mirror = true;
      setRotation(ClawPart2, 0.7853982F, 0F, 0F);
      ClawPart3 = new ModelRenderer(this, 20, 16);
      ClawPart3.addBox(0F, 0F, 0F, 1, 3, 1);
      ClawPart3.setRotationPoint(-8F, 5.3F, -0.7F);
      ClawPart3.setTextureSize(64, 64);
      ClawPart3.mirror = true;
      setRotation(ClawPart3, -0.7853982F, 0F, 0F);
      ClawPart4 = new ModelRenderer(this, 20, 16);
      ClawPart4.addBox(0F, 0F, 0F, 1, 3, 1);
      ClawPart4.setRotationPoint(-8F, 8F, 3F);
      ClawPart4.setTextureSize(64, 64);
      ClawPart4.mirror = true;
      setRotation(ClawPart4, 0F, 0F, 0F);
      ClawPart5 = new ModelRenderer(this, 20, 16);
      ClawPart5.addBox(0F, 0F, 0F, 1, 3, 1);
      ClawPart5.setRotationPoint(-8F, 8F, -3F);
      ClawPart5.setTextureSize(64, 64);
      ClawPart5.mirror = true;
      setRotation(ClawPart5, 0F, 0F, 0F);
      SightF = new ModelRenderer(this, 24, 16);
      SightF.addBox(0F, 0F, 0F, 1, 3, 1);
      SightF.setRotationPoint(7F, 2F, -3F);
      SightF.setTextureSize(64, 64);
      SightF.mirror = true;
      setRotation(SightF, 0F, 0F, 0F);
      SightB = new ModelRenderer(this, 24, 16);
      SightB.addBox(0F, 0F, 0F, 1, 3, 1);
      SightB.setRotationPoint(7F, 2F, 3F);
      SightB.setTextureSize(64, 64);
      SightB.mirror = true;
      setRotation(SightB, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 36, 52);
      Head.addBox(0F, 0F, 0F, 6, 6, 6);
      Head.setRotationPoint(-3F, -18F, -3F);
      Head.setTextureSize(64, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      AntenaL = new ModelRenderer(this, 50, 15);
      AntenaL.addBox(0F, 0F, 0F, 1, 5, 1);
      AntenaL.setRotationPoint(3F, -15F, 4F);
      AntenaL.setTextureSize(64, 64);
      AntenaL.mirror = true;
      setRotation(AntenaL, 0F, 0F, 0F);
      AntenaR = new ModelRenderer(this, 50, 15);
      AntenaR.addBox(0F, 0F, 0F, 1, 5, 1);
      AntenaR.setRotationPoint(-4F, -15F, 4F);
      AntenaR.setTextureSize(64, 64);
      AntenaR.mirror = true;
      setRotation(AntenaR, 0F, 0F, 0F);
      ExoSpineB = new ModelRenderer(this, 56, 26);
      ExoSpineB.addBox(0F, 0F, 0F, 2, 10, 1);
      ExoSpineB.setRotationPoint(-1F, -6F, 3F);
      ExoSpineB.setTextureSize(64, 64);
      ExoSpineB.mirror = true;
      setRotation(ExoSpineB, 0F, 0F, 0F);
      ExoSpineF = new ModelRenderer(this, 56, 15);
      ExoSpineF.addBox(0F, 0F, 0F, 2, 10, 1);
      ExoSpineF.setRotationPoint(-1F, -6F, -3F);
      ExoSpineF.setTextureSize(64, 64);
      ExoSpineF.mirror = true;
      setRotation(ExoSpineF, 0F, 0F, 0F);
      Chip = new ModelRenderer(this, 28, 17);
      Chip.addBox(0F, 0F, 0F, 2, 2, 1);
      Chip.setRotationPoint(-1F, -16F, 3F);
      Chip.setTextureSize(64, 64);
      Chip.mirror = true;
      setRotation(Chip, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    LegL.render(f5);
    LegR.render(f5);
    FootL.render(f5);
    FootR.render(f5);
    HeelL.render(f5);
    HeelR.render(f5);
    Hip.render(f5);
    Torso.render(f5);
    Chest.render(f5);
    ShoulderL.render(f5);
    ShoulderR.render(f5);
    Neck.render(f5);
    UpperArmL.render(f5);
    UpperArmR.render(f5);
    ForeArmL.render(f5);
    ForeArmR.render(f5);
    ClawPart1.render(f5);
    ClawPart2.render(f5);
    ClawPart3.render(f5);
    ClawPart4.render(f5);
    ClawPart5.render(f5);
    SightF.render(f5);
    SightB.render(f5);
    Head.render(f5);
    AntenaL.render(f5);
    AntenaR.render(f5);
    ExoSpineB.render(f5);
    ExoSpineF.render(f5);
    Chip.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Head.rotateAngleY = f4 / (180F / (float)Math.PI);
    Head.rotateAngleX = f5 / (180F / (float)Math.PI);
  }

}
